### ISSUE TITLE
1.12 Bossbars

### ISSUE THREAD

**Issue by Razorix06** [Weefle/SkWaze#2]
Hello ! I have a little problem, 1.12 bossbars doesn't work with me :/
I have the last version of Skript/Spigot and your addon

Error :
`[20:58:15 ERROR]: Can't understand this condition/effect: waze remove bossbar of player (starosia.sk, line 239: waze remove bossbar of player')
[20:58:15 ERROR]: Can't understand this condition/effect: waze create bossbar "ºbHydratation" at 100 percent with color blue for player (starosia.sk, line 241: waze create bossbar "ºbHydratation" at 100 percent with color blue for player')`

Code :
```
on join:
	waze remove bossbar of player
	wait 1 tick
	waze create bossbar "§bHydratation" at 100 percent with color blue for player
```

Thank you for reading this and btw sorry for my english I'm french ^^'

**Comment by Weefle** [comment]
Yes, I worked on bossbar before my vacations but I have nous access to my computer to release the update but I fixed the bossbar, sorry, the update will be here around the 14 of August 😄
Sorry for my bad english

**Comment by Razorix06** [comment]
D'accord pas de problème, parce-que j'avais essayé avec Skellet et SkRayFall mais rien ne fonctionne x)
Bah j'ai hâte d'être le 14 alors xD

**Comment by Weefle** [comment]
Sinon les bossbars devrait quand même fonctionner mais j'ai réglé les problème de conflit de bossbars, maintenant on pourra en mettre plusieurs ( a partir de la 1.9) et au lieu de mettre 1 on pourra mettre 100%, car oui si tu essaie: waze create bossbar "test" at 1 percent with coloris "BLUE" for player cela fonctionne normalement
Dans la dernière maj j'ai aussi fais en sorte qu'on puisse envoyer les bossbars a plusieurs joueurs sans avoir a utiliser le loop 😉

**Comment by Razorix06** [comment]
J'ai tout essayé pour les bossbars, mais les seules solutions qui marchaient été avec Skellet et skRayFall, mais je pouvais pas changer les pourcentages et ça me bourrait la console d'erreurs, j'ai donc voulu tester ton addon, car apparemment il fonctionnait en 1.12, mais rien ne marche :/ (Enfin j'ai pas testé les autres features, seulement les bossbars)

**Comment by Weefle** [comment]
Tu es sûr que ces syntaxes ne fonctionnent pas:
[waze] (create|send) [boss]bar %string% (with|at) %double% percent[s] (and|with) color %string% with id %string% (to|for) %players%

[waze] (create|send) [boss]bar %string% (with|at) %double% percent[s] (and|with) color %string% with id %string% (for|and) %integer% tick[s] (to|for) %players%

**Comment by Weefle** [comment]
Met 1.0 a la place de 100

**Comment by Razorix06** [comment]
Dans mon code j'avais pas mis la couleur entre "" et j'ai pas ajouté d'id, maintenant que c'est fait, j'ai plus d'erreur, mais ça ne fonctionne toujours pas, voilà ce que ça me met dans les logs:
`09.08 13:33:32 [Server] ERROR #!#!
09.08 13:33:32 [Server] ERROR #!#! [Skript] Severe Error:
09.08 13:33:32 [Server] ERROR #!#!
09.08 13:33:32 [Server] ERROR #!#! Something went horribly wrong with Skript.
09.08 13:33:32 [Server] ERROR #!#! This issue is NOT your fault! You probably can't fix it yourself, either. 09.08 13:33:32 [Server] ERROR #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
09.08 13:33:32 [Server] ERROR #!#! Here is full list of them:
09.08 13:33:32 [Server] ERROR #!#! skript-ping skRayFall (http://sk.rayfall.net/) TuSKe (github.com/Tuke-Nuke/TuSKe) skDragon SkStuff skUtilities (https://tim740.github.io/) skript-yaml SkQuery Skellett (https://forums.skunity.com/resources/skellett-the-addon-with-a-beast-name.24/) SkUniversal AdvancementsAddon
09.08 13:33:32 [Server] ERROR #!#! We could not identify which of those are specially related, so this might also be Skript issue.
09.08 13:33:32 [Server] ERROR #!#! You should try disabling those plugins one by one, trying to find which one causes it.
09.08 13:33:32 [Server] ERROR #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
09.08 13:33:32 [Server] ERROR #!#! In that case, you will be given instruction on how should you report it.
09.08 13:33:32 [Server] ERROR #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
09.08 13:33:32 [Server] ERROR #!#! Only if the author tells you to do so, report it as Skript issue (url below)
09.08 13:33:32 [Server] ERROR #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
09.08 13:33:32 [Server] ERROR #!#!
09.08 13:33:32 [Server] ERROR #!#! Stack trace:
09.08 13:33:32 [Server] ERROR #!#! java.lang.IllegalArgumentException: No enum constant org.bukkit.boss.BarColor.blue
09.08 13:33:32 [Server] ERROR #!#! at java.lang.Enum.valueOf(Enum.java:238)
09.08 13:33:32 [Server] ERROR #!#! at org.bukkit.boss.BarColor.valueOf(BarColor.java:1)
09.08 13:33:32 [Server] ERROR #!#! at fr.weefle.waze.nms.BossBarNew.sendBossBar(BossBarNew.java:33)
09.08 13:33:32 [Server] ERROR #!#! at fr.weefle.waze.effects.WazeEffectBossBarCreate.execute(WazeEffectBossBarCreate.java:41)
09.08 13:33:32 [Server] ERROR #!#! at ch.njol.skript.lang.Effect.run(Effect.java:52)
09.08 13:33:32 [Server] ERROR #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
09.08 13:33:32 [Server] ERROR #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
09.08 13:33:32 [Server] ERROR #!#! at ch.njol.skript.effects.Delay$1.run(Delay.java:109)
09.08 13:33:32 [Server] ERROR #!#! at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
09.08 13:33:32 [Server] ERROR #!#! at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361)
09.08 13:33:32 [Server] ERROR #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
09.08 13:33:32 [Server] ERROR #!#! at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
09.08 13:33:32 [Server] ERROR #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
09.08 13:33:32 [Server] ERROR #!#! at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
09.08 13:33:32 [Server] ERROR #!#! at java.lang.Thread.run(Thread.java:748)
09.08 13:33:32 [Server] ERROR #!#! 09.08 13:33:32 [Server] ERROR #!#! Version Information:
09.08 13:33:32 [Server] ERROR #!#! Skript: 2.2-dev37c (latest)
09.08 13:33:32 [Server] ERROR #!#! Bukkit: 1.12.2-R0.1-SNAPSHOT
09.08 13:33:32 [Server] ERROR #!#! Minecraft: 1.12.2
09.08 13:33:32 [Server] ERROR #!#! Java: 1.8.0_171 (Java HotSpot(TM) 64-Bit Server VM 25.171-b11) 09.08 13:33:32 [Server] ERROR #!#! OS: Linux amd64 4.9.0-6-amd64
09.08 13:33:32 [Server] ERROR #!#!
09.08 13:33:32 [Server] ERROR #!#! Server platform: Spigot
09.08 13:33:32 [Server] ERROR #!#!
09.08 13:33:32 [Server] ERROR #!#! Current node: null
09.08 13:33:32 [Server] ERROR #!#! Current item: send bossbar to player
09.08 13:33:32 [Server] ERROR #!#! Current trigger: join (simple event) (Survie.sk, line 5)
09.08 13:33:32 [Server] ERROR #!#!
09.08 13:33:32 [Server] ERROR #!#! Thread: Server thread
09.08 13:33:32 [Server] ERROR #!#!
09.08 13:33:32 [Server] ERROR #!#! Language: english
09.08 13:33:32 [Server] ERROR #!#! Link parse mode: DISABLED
09.08 13:33:32 [Server] ERROR #!#!
09.08 13:33:32 [Server] ERROR #!#! End of Error. 09.08 13:33:32 [Server] ERROR #!#! `

**Comment by Weefle** [comment]
Je suis sur mon portable et je rentre demain de vacances, je jetterai un coup d'oeil a ça et je mettrai en ligne la maj

**Comment by Razorix06** [comment]
Ok merci mec

**Comment by Weefle** [comment]
J'ai du retard mais tiens mon discord pour parler: Weefle#2074
